#!/usr/bin/env python3
"""Generate the per-language documentation pages under ``docs/languages/``.

The pages are **generated, never hand-edited**, so the supported-OS / supported-version
information cannot drift from the source of truth:

* **OS + example versions** come from each language's matrix JSON
  (``examples/<lang>/<lang>_project_matrix.json``; Python uses
  ``tests/python_project_matrix.json``). Those matrices are what the dynamic-update
  feature maintains, so refreshing them (by hand or via the tooling) and re-running this
  generator keeps the docs in sync.
* **The setup-action snippet** is extracted live from each ``<lang>_test.yml`` workflow
  and rewritten from the SHA pin to the version tag (matching the docs convention that
  ``sync_doc_action_refs.py`` enforces), so a Dependabot action bump flows into the docs.
* **The dynamically-maintained ``stable`` / ``latest``** versions come from the version
  cache (``.github/json2vars-setter/cache/version_cache.json``), which the
  ``Refresh data files`` workflow refreshes from the live release APIs (dynamic update).

Run modes:
* ``python .github/scripts/gen_language_docs.py``         -> (re)write the pages
* ``python .github/scripts/gen_language_docs.py --check``  -> exit 1 if any page is stale

The ``gen-language-docs`` pre-commit hook runs the writer on local commits that touch a
source; ``sync-language-docs.yml`` re-runs it on pushes to ``main``.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import cast

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs" / "languages"
WORKFLOWS = REPO_ROOT / ".github" / "workflows"
CACHE_FILE = REPO_ROOT / ".github" / "json2vars-setter" / "cache" / "version_cache.json"

REPO_BLOB = "https://github.com/7rikazhexde/json2vars-setter/blob/main"
REPO_TREE = "https://github.com/7rikazhexde/json2vars-setter/tree/main"

GENERATED_MARKER = (
    "<!-- AUTO-GENERATED by .github/scripts/gen_language_docs.py - DO NOT EDIT.\n"
    "     Edit the source matrix JSON / workflow and re-run the generator instead. -->"
)


@dataclass(frozen=True)
class Lang:
    slug: str  # matrix version key == output suffix == strategy prefix
    display: str
    # action repo to locate the setup step in the workflow; None => locate by step name
    action_repo: str | None
    # matrix JSON path relative to the repo root
    matrix: str
    # example project dir relative to the repo root (None => no dedicated example dir)
    example_dir: str | None
    note: str = ""
    # step name fallback when there is no setup action (Kotlin)
    step_name: str = ""


# Order mirrors README / docs/index language table (primary languages first).
LANGS: list[Lang] = [
    Lang(
        "python",
        "Python",
        "actions/setup-python",
        "tests/python_project_matrix.json",
        None,
        note="The project under test is json2vars-setter itself, so Python uses the "
        "repository's own `tests/python_project_matrix.json` rather than a "
        "dedicated `examples/` project.",
    ),
    Lang(
        "nodejs",
        "Node.js",
        "actions/setup-node",
        "examples/nodejs/nodejs_project_matrix.json",
        "examples/nodejs",
    ),
    Lang(
        "ruby",
        "Ruby",
        "ruby/setup-ruby",
        "examples/ruby/ruby_project_matrix.json",
        "examples/ruby",
    ),
    Lang(
        "go",
        "Go",
        "actions/setup-go",
        "examples/go/go_project_matrix.json",
        "examples/go",
    ),
    Lang(
        "rust",
        "Rust",
        "dtolnay/rust-toolchain",
        "examples/rust/rust_project_matrix.json",
        "examples/rust",
    ),
    Lang(
        "php",
        "PHP",
        "shivammathur/setup-php",
        "examples/php/php_project_matrix.json",
        "examples/php",
    ),
    Lang(
        "dotnet",
        ".NET (C#)",
        "actions/setup-dotnet",
        "examples/dotnet/dotnet_project_matrix.json",
        "examples/dotnet",
    ),
    Lang(
        "java",
        "Java",
        "actions/setup-java",
        "examples/java/java_project_matrix.json",
        "examples/java",
    ),
    Lang(
        "deno",
        "Deno",
        "denoland/setup-deno",
        "examples/deno/deno_project_matrix.json",
        "examples/deno",
    ),
    Lang(
        "bun",
        "Bun",
        "oven-sh/setup-bun",
        "examples/bun/bun_project_matrix.json",
        "examples/bun",
    ),
    Lang(
        "zig",
        "Zig",
        "mlugg/setup-zig",
        "examples/zig/zig_project_matrix.json",
        "examples/zig",
    ),
    Lang(
        "elixir",
        "Elixir",
        "erlef/setup-beam",
        "examples/elixir/elixir_project_matrix.json",
        "examples/elixir",
        note="`erlef/setup-beam` also needs an Erlang/OTP version, pinned separately in "
        "the workflow. On `windows-latest` the runner image now reports "
        "`ImageOS=win25-vs2026`; setup-beam v1.24.0 only maps the bare `win25` "
        "label, so the workflow normalizes it (`win25-vs2026` -> `win25`) in a "
        "Windows-only step before the setup action runs.",
    ),
    Lang(
        "dart",
        "Dart",
        "dart-lang/setup-dart",
        "examples/dart/dart_project_matrix.json",
        "examples/dart",
    ),
    Lang(
        "swift",
        "Swift",
        "swift-actions/setup-swift",
        "examples/swift/swift_project_matrix.json",
        "examples/swift",
        note="`swift-actions/setup-swift` installs from its own bundled list of known "
        "Swift versions, which can lag the newest swift.org release - pin to a "
        "version the action supports if the very latest is not yet available.",
    ),
    Lang(
        "julia",
        "Julia",
        "julia-actions/setup-julia",
        "examples/julia/julia_project_matrix.json",
        "examples/julia",
    ),
    Lang(
        "crystal",
        "Crystal",
        "crystal-lang/install-crystal",
        "examples/crystal/crystal_project_matrix.json",
        "examples/crystal",
    ),
    Lang(
        "haskell",
        "Haskell",
        "haskell-actions/setup",
        "examples/haskell/haskell_project_matrix.json",
        "examples/haskell",
    ),
    Lang(
        "ocaml",
        "OCaml",
        "ocaml/setup-ocaml",
        "examples/ocaml/ocaml_project_matrix.json",
        "examples/ocaml",
    ),
    Lang(
        "kotlin",
        "Kotlin",
        None,
        "examples/kotlin/kotlin_project_matrix.json",
        "examples/kotlin",
        note="There is no official Kotlin setup action, so the workflow downloads the "
        "exact `kotlin-compiler-<version>.zip` from the matching JetBrains release, "
        "verifies its published SHA-256, and adds `kotlinc` to `PATH`.",
        step_name="Set up Kotlin",
    ),
    Lang(
        "clang",
        "Clang / LLVM",
        "aminya/setup-cpp",
        "examples/clang/clang_project_matrix.json",
        "examples/clang",
        note="`aminya/setup-cpp` is the de-facto cross-platform compiler installer (no "
        "official Clang setup action exists); it exports `CC`/`CXX` pointing at the "
        "installed LLVM clang. The C++ *standard* (`-std=c++20`, ...) is a static "
        "list you hand-write in the matrix JSON - it needs no fetcher.",
    ),
    Lang(
        "gcc",
        "GCC",
        "aminya/setup-cpp",
        "examples/gcc/gcc_project_matrix.json",
        "examples/gcc",
        note="`aminya/setup-cpp` installs a specific GCC and exports `CC`/`CXX`. GCC's "
        "packaging is by major version, so the example matrix pins majors.",
    ),
    Lang(
        "flutter",
        "Flutter",
        "subosito/flutter-action",
        "examples/flutter/flutter_project_matrix.json",
        "examples/flutter",
        note="Flutter bundles its own Dart SDK and is tracked separately from Dart.",
    ),
]

OS_LABELS = {
    "ubuntu-latest": "Ubuntu",
    "windows-latest": "Windows",
    "macos-latest": "macOS",
}


def load_matrix(rel_path: str) -> tuple[list[str], list[str]]:
    data = json.loads((REPO_ROOT / rel_path).read_text(encoding="utf-8"))
    os_list = list(data.get("os", []))
    versions = data.get("versions", {})
    # the version key is the only key under "versions"
    vlist = next(iter(versions.values())) if versions else []
    return os_list, list(vlist)


_USES_PIN = re.compile(r"^(?P<pre>.*uses:\s*\S+?)@\S+\s+#\s*(?P<ver>\S+)\s*$")


def _rewrite_uses(line: str) -> str:
    """Rewrite ``uses: owner/repo@<sha> # v1.2.3`` -> ``uses: owner/repo@v1.2.3``."""
    m = _USES_PIN.match(line.rstrip())
    if m:
        return f"{m.group('pre')}@{m.group('ver')}"
    return line.rstrip()


def extract_setup_step(lang: Lang) -> str:
    """Pull the language's setup step out of its workflow as a clean YAML snippet."""
    wf = WORKFLOWS / f"{lang.slug}_test.yml"
    lines = wf.read_text(encoding="utf-8").splitlines()

    # locate the anchor line
    idx = None
    if lang.action_repo:
        needle = re.compile(r"uses:\s*" + re.escape(lang.action_repo) + r"@")
        for i, ln in enumerate(lines):
            if needle.search(ln):
                idx = i
                break
    else:
        needle = re.compile(r"-\s*name:\s*" + re.escape(lang.step_name))
        for i, ln in enumerate(lines):
            if needle.search(ln):
                idx = i
                break
    if idx is None:  # pragma: no cover - guards against workflow drift
        raise SystemExit(f"could not locate setup step for {lang.slug} in {wf}")

    # walk back to the start of the list item ("- name:" / "- uses:")
    start = idx
    while start >= 0 and not re.match(r"^\s*-\s", lines[start]):
        start -= 1
    indent = len(lines[start]) - len(lines[start].lstrip())

    # walk forward to the next list item at the same indent
    end = start + 1
    item_at_indent = re.compile(r"^ {" + str(indent) + r"}-\s")
    while end < len(lines) and not item_at_indent.match(lines[end]):
        end += 1

    block = lines[start:end]
    out: list[str] = []
    for ln in block:
        if ln.strip().startswith("#"):  # drop full-line comments
            continue
        ln = _rewrite_uses(ln)
        out.append(ln[indent:] if len(ln) >= indent else ln)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out)


def load_cache() -> dict[str, dict[str, object]]:
    if not CACHE_FILE.exists():
        return {}
    data = json.loads(CACHE_FILE.read_text(encoding="utf-8"))
    return cast("dict[str, dict[str, object]]", data.get("languages", {}))


def render_page(lang: Lang, cache: dict[str, dict[str, object]]) -> str:
    os_list, versions = load_matrix(lang.matrix)
    os_rendered = ", ".join(f"`{o}`" for o in os_list)
    os_human = " / ".join(OS_LABELS.get(o, o) for o in os_list)
    # Pretty-print (indented, multi-line) so the snippet is readable / copy-pasteable.
    versions_block = json.dumps({"versions": {lang.slug: versions}}, indent=2)

    lines: list[str] = []
    lines.append(f"# {lang.display}")
    lines.append("")
    lines.append(GENERATED_MARKER)
    lines.append("")
    lines.append(
        f"How `json2vars-setter` handles {lang.display}, and how the example workflow "
        "provisions it."
    )
    lines.append("")

    # integration table
    lines.append("## json2vars-setter integration")
    lines.append("")
    lines.append("| Item | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Matrix JSON key | `versions.{lang.slug}` |")
    lines.append(f"| Action output | `versions_{lang.slug}` |")
    lines.append(
        f"| Dynamic-update strategy input | `{lang.slug}-strategy` "
        "(`stable` / `latest` / `both`) |"
    )
    lines.append(
        "| Version source | see [Version Sources](../reference/version-sources.md) |"
    )
    lines.append("")

    # supported runners
    lines.append("## Supported runners")
    lines.append("")
    lines.append(f"The example matrix runs on **{os_human}**:")
    lines.append("")
    lines.append(os_rendered)
    lines.append("")
    lines.append(
        "Any GitHub-hosted runner the setup action supports also works - the OS list is "
        "just the `os` array in your matrix JSON."
    )
    lines.append("")

    # versions
    lines.append("## Supported versions")
    lines.append("")
    lines.append("Example matrix (what the example workflow runs):")
    lines.append("")
    lines.append("```json")
    lines.extend(versions_block.splitlines())
    lines.append("```")
    lines.append("")

    info = cache.get(lang.slug)
    if info and (info.get("stable") or info.get("latest")):
        lines.append(
            "Latest values tracked by the dynamic-update tooling "
            "(auto-refreshed from the release APIs into the version cache):"
        )
        lines.append("")
        lines.append("| Field | Version |")
        lines.append("| --- | --- |")
        if info.get("stable"):
            lines.append(f"| `stable` | `{info['stable']}` |")
        if info.get("latest"):
            lines.append(f"| `latest` | `{info['latest']}` |")
        lines.append("")
        if info.get("last_updated"):
            lines.append(f"_Cache last updated: {info['last_updated']}._")
            lines.append("")
    else:
        lines.append(
            "> Enable dynamic update (`" + lang.slug + "-strategy`) to have "
            "json2vars-setter fill these in from the latest releases. The "
            "`stable` / `latest` values for this language are populated into the "
            "version cache by the **Refresh data files** workflow."
        )
        lines.append("")

    # setup action
    lines.append("## Setup action (example workflow)")
    lines.append("")
    wf_rel = f".github/workflows/{lang.slug}_test.yml"
    lines.append(
        f"[`{lang.slug}_test.yml`]({REPO_BLOB}/{wf_rel}) provisions {lang.display} "
        "with the matrix value json2vars-setter produced:"
    )
    lines.append("")
    lines.append("```yaml")
    lines.append(extract_setup_step(lang))
    lines.append("```")
    lines.append("")
    if lang.note:
        lines.append(f"> **Note:** {lang.note}")
        lines.append("")

    # references
    lines.append("## References")
    lines.append("")
    if lang.example_dir:
        lines.append(
            f"- Example project: [`{lang.example_dir}/`]({REPO_TREE}/{lang.example_dir})"
        )
    lines.append(f"- Example workflow: [`{wf_rel}`]({REPO_BLOB}/{wf_rel})")
    lines.append(f"- Matrix JSON: [`{lang.matrix}`]({REPO_BLOB}/{lang.matrix})")
    lines.append("")

    return "\n".join(lines)


def render_index() -> str:
    lines: list[str] = []
    lines.append("# Languages")
    lines.append("")
    lines.append(GENERATED_MARKER)
    lines.append("")
    lines.append(
        "Per-language reference: the runners and versions each example exercises, and the "
        "setup action json2vars-setter drives. Supported versions are kept in sync with "
        "the matrix JSON and the dynamic-update version cache - these pages are generated, "
        "not hand-written."
    )
    lines.append("")
    lines.append("| Language | Runners | Setup action |")
    lines.append("| --- | --- | --- |")
    for lang in LANGS:
        os_list, _ = load_matrix(lang.matrix)
        os_human = " / ".join(OS_LABELS.get(o, o) for o in os_list)
        action = f"`{lang.action_repo}`" if lang.action_repo else "direct download"
        lines.append(f"| [{lang.display}]({lang.slug}.md) | {os_human} | {action} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any generated page is out of date (no writes)",
    )
    args = parser.parse_args(argv)

    cache = load_cache()
    # Exactly one trailing newline so the output is stable under end-of-file-fixer.
    targets: dict[Path, str] = {
        DOCS_DIR / "index.md": render_index().rstrip("\n") + "\n"
    }
    for lang in LANGS:
        targets[DOCS_DIR / f"{lang.slug}.md"] = (
            render_page(lang, cache).rstrip("\n") + "\n"
        )

    stale: list[Path] = []
    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")

    if args.check and stale:
        rel = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"Language docs are out of date: {rel}", file=sys.stderr)
        print("Run: python .github/scripts/gen_language_docs.py", file=sys.stderr)
        return 1
    if not args.check and stale:
        rel = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"Updated: {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
